dist: xenial
sudo: required
language: go

env:
  global:
    - GOFLAGS=-mod=vendor

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Code Lint"
      script: make lint
    - go: "1.13.x"
      name: "Code UnitTest"
      script: make test
    - go: "1.13.x"
      name: "Generated Code is Current"
      script: make gen && git diff --quiet

install:
  - make tools
  - go mod vendor

# branches:
#   only:
#     - master
