// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePermissionsIDParams creates a new DeletePermissionsIDParams object
// with the default values initialized.
func NewDeletePermissionsIDParams() *DeletePermissionsIDParams {
	var ()
	return &DeletePermissionsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePermissionsIDParamsWithTimeout creates a new DeletePermissionsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePermissionsIDParamsWithTimeout(timeout time.Duration) *DeletePermissionsIDParams {
	var ()
	return &DeletePermissionsIDParams{

		timeout: timeout,
	}
}

// NewDeletePermissionsIDParamsWithContext creates a new DeletePermissionsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePermissionsIDParamsWithContext(ctx context.Context) *DeletePermissionsIDParams {
	var ()
	return &DeletePermissionsIDParams{

		Context: ctx,
	}
}

// NewDeletePermissionsIDParamsWithHTTPClient creates a new DeletePermissionsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePermissionsIDParamsWithHTTPClient(client *http.Client) *DeletePermissionsIDParams {
	var ()
	return &DeletePermissionsIDParams{
		HTTPClient: client,
	}
}

/*DeletePermissionsIDParams contains all the parameters to send to the API endpoint
for the delete permissions ID operation typically these are written to a http.Request
*/
type DeletePermissionsIDParams struct {

	/*ID
	  id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete permissions ID params
func (o *DeletePermissionsIDParams) WithTimeout(timeout time.Duration) *DeletePermissionsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete permissions ID params
func (o *DeletePermissionsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete permissions ID params
func (o *DeletePermissionsIDParams) WithContext(ctx context.Context) *DeletePermissionsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete permissions ID params
func (o *DeletePermissionsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete permissions ID params
func (o *DeletePermissionsIDParams) WithHTTPClient(client *http.Client) *DeletePermissionsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete permissions ID params
func (o *DeletePermissionsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete permissions ID params
func (o *DeletePermissionsIDParams) WithID(id int64) *DeletePermissionsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete permissions ID params
func (o *DeletePermissionsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePermissionsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
