// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/reggregory/go-deploy/models"
)

// DeletePermissionsIDReader is a Reader for the DeletePermissionsID structure.
type DeletePermissionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePermissionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePermissionsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePermissionsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePermissionsIDNoContent creates a DeletePermissionsIDNoContent with default headers values
func NewDeletePermissionsIDNoContent() *DeletePermissionsIDNoContent {
	return &DeletePermissionsIDNoContent{}
}

/*DeletePermissionsIDNoContent handles this case with default header values.

successful
*/
type DeletePermissionsIDNoContent struct {
}

func (o *DeletePermissionsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /permissions/{id}][%d] deletePermissionsIdNoContent ", 204)
}

func (o *DeletePermissionsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePermissionsIDDefault creates a DeletePermissionsIDDefault with default headers values
func NewDeletePermissionsIDDefault(code int) *DeletePermissionsIDDefault {
	return &DeletePermissionsIDDefault{
		_statusCode: code,
	}
}

/*DeletePermissionsIDDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type DeletePermissionsIDDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the delete permissions ID default response
func (o *DeletePermissionsIDDefault) Code() int {
	return o._statusCode
}

func (o *DeletePermissionsIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /permissions/{id}][%d] DeletePermissionsID default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePermissionsIDDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *DeletePermissionsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
