// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aptible/go-deploy/models"
)

// DeleteVhostsIDReader is a Reader for the DeleteVhostsID structure.
type DeleteVhostsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVhostsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteVhostsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteVhostsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteVhostsIDNoContent creates a DeleteVhostsIDNoContent with default headers values
func NewDeleteVhostsIDNoContent() *DeleteVhostsIDNoContent {
	return &DeleteVhostsIDNoContent{}
}

/* DeleteVhostsIDNoContent describes a response with status code 204, with default header values.

successful
*/
type DeleteVhostsIDNoContent struct {
}

func (o *DeleteVhostsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /vhosts/{id}][%d] deleteVhostsIdNoContent ", 204)
}

func (o *DeleteVhostsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteVhostsIDDefault creates a DeleteVhostsIDDefault with default headers values
func NewDeleteVhostsIDDefault(code int) *DeleteVhostsIDDefault {
	return &DeleteVhostsIDDefault{
		_statusCode: code,
	}
}

/* DeleteVhostsIDDefault describes a response with status code -1, with default header values.

Error response. Often a 4xx or 5xx status code
*/
type DeleteVhostsIDDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the delete vhosts ID default response
func (o *DeleteVhostsIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteVhostsIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /vhosts/{id}][%d] DeleteVhostsID default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteVhostsIDDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *DeleteVhostsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
