// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteVhostsIDParams creates a new DeleteVhostsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteVhostsIDParams() *DeleteVhostsIDParams {
	return &DeleteVhostsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVhostsIDParamsWithTimeout creates a new DeleteVhostsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteVhostsIDParamsWithTimeout(timeout time.Duration) *DeleteVhostsIDParams {
	return &DeleteVhostsIDParams{
		timeout: timeout,
	}
}

// NewDeleteVhostsIDParamsWithContext creates a new DeleteVhostsIDParams object
// with the ability to set a context for a request.
func NewDeleteVhostsIDParamsWithContext(ctx context.Context) *DeleteVhostsIDParams {
	return &DeleteVhostsIDParams{
		Context: ctx,
	}
}

// NewDeleteVhostsIDParamsWithHTTPClient creates a new DeleteVhostsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteVhostsIDParamsWithHTTPClient(client *http.Client) *DeleteVhostsIDParams {
	return &DeleteVhostsIDParams{
		HTTPClient: client,
	}
}

/* DeleteVhostsIDParams contains all the parameters to send to the API endpoint
   for the delete vhosts ID operation.

   Typically these are written to a http.Request.
*/
type DeleteVhostsIDParams struct {

	/* ID.

	   id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete vhosts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVhostsIDParams) WithDefaults() *DeleteVhostsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete vhosts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVhostsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete vhosts ID params
func (o *DeleteVhostsIDParams) WithTimeout(timeout time.Duration) *DeleteVhostsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete vhosts ID params
func (o *DeleteVhostsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete vhosts ID params
func (o *DeleteVhostsIDParams) WithContext(ctx context.Context) *DeleteVhostsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete vhosts ID params
func (o *DeleteVhostsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete vhosts ID params
func (o *DeleteVhostsIDParams) WithHTTPClient(client *http.Client) *DeleteVhostsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete vhosts ID params
func (o *DeleteVhostsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete vhosts ID params
func (o *DeleteVhostsIDParams) WithID(id int64) *DeleteVhostsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete vhosts ID params
func (o *DeleteVhostsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVhostsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
