// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteCertificatesIDParams creates a new DeleteCertificatesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCertificatesIDParams() *DeleteCertificatesIDParams {
	return &DeleteCertificatesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCertificatesIDParamsWithTimeout creates a new DeleteCertificatesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteCertificatesIDParamsWithTimeout(timeout time.Duration) *DeleteCertificatesIDParams {
	return &DeleteCertificatesIDParams{
		timeout: timeout,
	}
}

// NewDeleteCertificatesIDParamsWithContext creates a new DeleteCertificatesIDParams object
// with the ability to set a context for a request.
func NewDeleteCertificatesIDParamsWithContext(ctx context.Context) *DeleteCertificatesIDParams {
	return &DeleteCertificatesIDParams{
		Context: ctx,
	}
}

// NewDeleteCertificatesIDParamsWithHTTPClient creates a new DeleteCertificatesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCertificatesIDParamsWithHTTPClient(client *http.Client) *DeleteCertificatesIDParams {
	return &DeleteCertificatesIDParams{
		HTTPClient: client,
	}
}

/* DeleteCertificatesIDParams contains all the parameters to send to the API endpoint
   for the delete certificates ID operation.

   Typically these are written to a http.Request.
*/
type DeleteCertificatesIDParams struct {

	/* ID.

	   id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete certificates ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCertificatesIDParams) WithDefaults() *DeleteCertificatesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete certificates ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCertificatesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete certificates ID params
func (o *DeleteCertificatesIDParams) WithTimeout(timeout time.Duration) *DeleteCertificatesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete certificates ID params
func (o *DeleteCertificatesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete certificates ID params
func (o *DeleteCertificatesIDParams) WithContext(ctx context.Context) *DeleteCertificatesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete certificates ID params
func (o *DeleteCertificatesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete certificates ID params
func (o *DeleteCertificatesIDParams) WithHTTPClient(client *http.Client) *DeleteCertificatesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete certificates ID params
func (o *DeleteCertificatesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete certificates ID params
func (o *DeleteCertificatesIDParams) WithID(id int64) *DeleteCertificatesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete certificates ID params
func (o *DeleteCertificatesIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCertificatesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
