// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams creates a new GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams object
// with the default values initialized.
func NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams() *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	var ()
	return &GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParamsWithTimeout creates a new GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParamsWithTimeout(timeout time.Duration) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	var ()
	return &GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams{

		timeout: timeout,
	}
}

// NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParamsWithContext creates a new GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParamsWithContext(ctx context.Context) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	var ()
	return &GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams{

		Context: ctx,
	}
}

// NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParamsWithHTTPClient creates a new GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParamsWithHTTPClient(client *http.Client) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	var ()
	return &GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams{
		HTTPClient: client,
	}
}

/*GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams contains all the parameters to send to the API endpoint
for the get intrusion detection reports intrusion report ID download csv operation typically these are written to a http.Request
*/
type GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams struct {

	/*IntrusionReportID
	  intrusion_report_id

	*/
	IntrusionReportID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) WithTimeout(timeout time.Duration) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) WithContext(ctx context.Context) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) WithHTTPClient(client *http.Client) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIntrusionReportID adds the intrusionReportID to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) WithIntrusionReportID(intrusionReportID int64) *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams {
	o.SetIntrusionReportID(intrusionReportID)
	return o
}

// SetIntrusionReportID adds the intrusionReportId to the get intrusion detection reports intrusion report ID download csv params
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) SetIntrusionReportID(intrusionReportID int64) {
	o.IntrusionReportID = intrusionReportID
}

// WriteToRequest writes these params to a swagger request
func (o *GetIntrusionDetectionReportsIntrusionReportIDDownloadCsvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param intrusion_report_id
	if err := r.SetPathParam("intrusion_report_id", swag.FormatInt64(o.IntrusionReportID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
