// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOperationsIDParams creates a new GetOperationsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOperationsIDParams() *GetOperationsIDParams {
	return &GetOperationsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOperationsIDParamsWithTimeout creates a new GetOperationsIDParams object
// with the ability to set a timeout on a request.
func NewGetOperationsIDParamsWithTimeout(timeout time.Duration) *GetOperationsIDParams {
	return &GetOperationsIDParams{
		timeout: timeout,
	}
}

// NewGetOperationsIDParamsWithContext creates a new GetOperationsIDParams object
// with the ability to set a context for a request.
func NewGetOperationsIDParamsWithContext(ctx context.Context) *GetOperationsIDParams {
	return &GetOperationsIDParams{
		Context: ctx,
	}
}

// NewGetOperationsIDParamsWithHTTPClient creates a new GetOperationsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOperationsIDParamsWithHTTPClient(client *http.Client) *GetOperationsIDParams {
	return &GetOperationsIDParams{
		HTTPClient: client,
	}
}

/* GetOperationsIDParams contains all the parameters to send to the API endpoint
   for the get operations ID operation.

   Typically these are written to a http.Request.
*/
type GetOperationsIDParams struct {

	/* ID.

	   id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get operations ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOperationsIDParams) WithDefaults() *GetOperationsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get operations ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOperationsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get operations ID params
func (o *GetOperationsIDParams) WithTimeout(timeout time.Duration) *GetOperationsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get operations ID params
func (o *GetOperationsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get operations ID params
func (o *GetOperationsIDParams) WithContext(ctx context.Context) *GetOperationsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get operations ID params
func (o *GetOperationsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get operations ID params
func (o *GetOperationsIDParams) WithHTTPClient(client *http.Client) *GetOperationsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get operations ID params
func (o *GetOperationsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get operations ID params
func (o *GetOperationsIDParams) WithID(id int64) *GetOperationsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get operations ID params
func (o *GetOperationsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetOperationsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
