// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetServicesIDReader is a Reader for the GetServicesID structure.
type GetServicesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServicesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServicesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetServicesIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetServicesIDOK creates a GetServicesIDOK with default headers values
func NewGetServicesIDOK() *GetServicesIDOK {
	return &GetServicesIDOK{}
}

/*GetServicesIDOK handles this case with default header values.

successful
*/
type GetServicesIDOK struct {
	Payload *models.InlineResponse20034
}

func (o *GetServicesIDOK) Error() string {
	return fmt.Sprintf("[GET /services/{id}][%d] getServicesIdOK  %+v", 200, o.Payload)
}

func (o *GetServicesIDOK) GetPayload() *models.InlineResponse20034 {
	return o.Payload
}

func (o *GetServicesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20034)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServicesIDDefault creates a GetServicesIDDefault with default headers values
func NewGetServicesIDDefault(code int) *GetServicesIDDefault {
	return &GetServicesIDDefault{
		_statusCode: code,
	}
}

/*GetServicesIDDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetServicesIDDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get services ID default response
func (o *GetServicesIDDefault) Code() int {
	return o._statusCode
}

func (o *GetServicesIDDefault) Error() string {
	return fmt.Sprintf("[GET /services/{id}][%d] GetServicesID default  %+v", o._statusCode, o.Payload)
}

func (o *GetServicesIDDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetServicesIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
