// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDisksIDParams creates a new GetDisksIDParams object
// with the default values initialized.
func NewGetDisksIDParams() *GetDisksIDParams {
	var ()
	return &GetDisksIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDisksIDParamsWithTimeout creates a new GetDisksIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDisksIDParamsWithTimeout(timeout time.Duration) *GetDisksIDParams {
	var ()
	return &GetDisksIDParams{

		timeout: timeout,
	}
}

// NewGetDisksIDParamsWithContext creates a new GetDisksIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDisksIDParamsWithContext(ctx context.Context) *GetDisksIDParams {
	var ()
	return &GetDisksIDParams{

		Context: ctx,
	}
}

// NewGetDisksIDParamsWithHTTPClient creates a new GetDisksIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDisksIDParamsWithHTTPClient(client *http.Client) *GetDisksIDParams {
	var ()
	return &GetDisksIDParams{
		HTTPClient: client,
	}
}

/*GetDisksIDParams contains all the parameters to send to the API endpoint
for the get disks ID operation typically these are written to a http.Request
*/
type GetDisksIDParams struct {

	/*ID
	  id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get disks ID params
func (o *GetDisksIDParams) WithTimeout(timeout time.Duration) *GetDisksIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get disks ID params
func (o *GetDisksIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get disks ID params
func (o *GetDisksIDParams) WithContext(ctx context.Context) *GetDisksIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get disks ID params
func (o *GetDisksIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get disks ID params
func (o *GetDisksIDParams) WithHTTPClient(client *http.Client) *GetDisksIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get disks ID params
func (o *GetDisksIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get disks ID params
func (o *GetDisksIDParams) WithID(id int64) *GetDisksIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get disks ID params
func (o *GetDisksIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDisksIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
