// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLogDrainsLogDrainIDEphemeralContainersParams creates a new GetLogDrainsLogDrainIDEphemeralContainersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLogDrainsLogDrainIDEphemeralContainersParams() *GetLogDrainsLogDrainIDEphemeralContainersParams {
	return &GetLogDrainsLogDrainIDEphemeralContainersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogDrainsLogDrainIDEphemeralContainersParamsWithTimeout creates a new GetLogDrainsLogDrainIDEphemeralContainersParams object
// with the ability to set a timeout on a request.
func NewGetLogDrainsLogDrainIDEphemeralContainersParamsWithTimeout(timeout time.Duration) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	return &GetLogDrainsLogDrainIDEphemeralContainersParams{
		timeout: timeout,
	}
}

// NewGetLogDrainsLogDrainIDEphemeralContainersParamsWithContext creates a new GetLogDrainsLogDrainIDEphemeralContainersParams object
// with the ability to set a context for a request.
func NewGetLogDrainsLogDrainIDEphemeralContainersParamsWithContext(ctx context.Context) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	return &GetLogDrainsLogDrainIDEphemeralContainersParams{
		Context: ctx,
	}
}

// NewGetLogDrainsLogDrainIDEphemeralContainersParamsWithHTTPClient creates a new GetLogDrainsLogDrainIDEphemeralContainersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLogDrainsLogDrainIDEphemeralContainersParamsWithHTTPClient(client *http.Client) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	return &GetLogDrainsLogDrainIDEphemeralContainersParams{
		HTTPClient: client,
	}
}

/* GetLogDrainsLogDrainIDEphemeralContainersParams contains all the parameters to send to the API endpoint
   for the get log drains log drain ID ephemeral containers operation.

   Typically these are written to a http.Request.
*/
type GetLogDrainsLogDrainIDEphemeralContainersParams struct {

	/* LogDrainID.

	   log_drain_id
	*/
	LogDrainID int64

	/* Page.

	   current page of results for pagination
	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get log drains log drain ID ephemeral containers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WithDefaults() *GetLogDrainsLogDrainIDEphemeralContainersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get log drains log drain ID ephemeral containers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WithTimeout(timeout time.Duration) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WithContext(ctx context.Context) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WithHTTPClient(client *http.Client) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLogDrainID adds the logDrainID to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WithLogDrainID(logDrainID int64) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	o.SetLogDrainID(logDrainID)
	return o
}

// SetLogDrainID adds the logDrainId to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) SetLogDrainID(logDrainID int64) {
	o.LogDrainID = logDrainID
}

// WithPage adds the page to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WithPage(page *int64) *GetLogDrainsLogDrainIDEphemeralContainersParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get log drains log drain ID ephemeral containers params
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogDrainsLogDrainIDEphemeralContainersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param log_drain_id
	if err := r.SetPathParam("log_drain_id", swag.FormatInt64(o.LogDrainID)); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
