// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParams creates a new GetDatabaseCredentialsDatabaseCredentialIDOperationsParams object
// with the default values initialized.
func NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParams() *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	var ()
	return &GetDatabaseCredentialsDatabaseCredentialIDOperationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParamsWithTimeout creates a new GetDatabaseCredentialsDatabaseCredentialIDOperationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParamsWithTimeout(timeout time.Duration) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	var ()
	return &GetDatabaseCredentialsDatabaseCredentialIDOperationsParams{

		timeout: timeout,
	}
}

// NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParamsWithContext creates a new GetDatabaseCredentialsDatabaseCredentialIDOperationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParamsWithContext(ctx context.Context) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	var ()
	return &GetDatabaseCredentialsDatabaseCredentialIDOperationsParams{

		Context: ctx,
	}
}

// NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParamsWithHTTPClient creates a new GetDatabaseCredentialsDatabaseCredentialIDOperationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDatabaseCredentialsDatabaseCredentialIDOperationsParamsWithHTTPClient(client *http.Client) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	var ()
	return &GetDatabaseCredentialsDatabaseCredentialIDOperationsParams{
		HTTPClient: client,
	}
}

/*GetDatabaseCredentialsDatabaseCredentialIDOperationsParams contains all the parameters to send to the API endpoint
for the get database credentials database credential ID operations operation typically these are written to a http.Request
*/
type GetDatabaseCredentialsDatabaseCredentialIDOperationsParams struct {

	/*DatabaseCredentialID
	  database_credential_id

	*/
	DatabaseCredentialID int64
	/*Page
	  current page of results for pagination

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) WithTimeout(timeout time.Duration) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) WithContext(ctx context.Context) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) WithHTTPClient(client *http.Client) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDatabaseCredentialID adds the databaseCredentialID to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) WithDatabaseCredentialID(databaseCredentialID int64) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	o.SetDatabaseCredentialID(databaseCredentialID)
	return o
}

// SetDatabaseCredentialID adds the databaseCredentialId to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) SetDatabaseCredentialID(databaseCredentialID int64) {
	o.DatabaseCredentialID = databaseCredentialID
}

// WithPage adds the page to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) WithPage(page *int64) *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get database credentials database credential ID operations params
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetDatabaseCredentialsDatabaseCredentialIDOperationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param database_credential_id
	if err := r.SetPathParam("database_credential_id", swag.FormatInt64(o.DatabaseCredentialID)); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
