// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReleasesReleaseIDContainersParams creates a new GetReleasesReleaseIDContainersParams object
// with the default values initialized.
func NewGetReleasesReleaseIDContainersParams() *GetReleasesReleaseIDContainersParams {
	var ()
	return &GetReleasesReleaseIDContainersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReleasesReleaseIDContainersParamsWithTimeout creates a new GetReleasesReleaseIDContainersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReleasesReleaseIDContainersParamsWithTimeout(timeout time.Duration) *GetReleasesReleaseIDContainersParams {
	var ()
	return &GetReleasesReleaseIDContainersParams{

		timeout: timeout,
	}
}

// NewGetReleasesReleaseIDContainersParamsWithContext creates a new GetReleasesReleaseIDContainersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReleasesReleaseIDContainersParamsWithContext(ctx context.Context) *GetReleasesReleaseIDContainersParams {
	var ()
	return &GetReleasesReleaseIDContainersParams{

		Context: ctx,
	}
}

// NewGetReleasesReleaseIDContainersParamsWithHTTPClient creates a new GetReleasesReleaseIDContainersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReleasesReleaseIDContainersParamsWithHTTPClient(client *http.Client) *GetReleasesReleaseIDContainersParams {
	var ()
	return &GetReleasesReleaseIDContainersParams{
		HTTPClient: client,
	}
}

/*GetReleasesReleaseIDContainersParams contains all the parameters to send to the API endpoint
for the get releases release ID containers operation typically these are written to a http.Request
*/
type GetReleasesReleaseIDContainersParams struct {

	/*Page
	  current page of results for pagination

	*/
	Page *int64
	/*ReleaseID
	  release_id

	*/
	ReleaseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) WithTimeout(timeout time.Duration) *GetReleasesReleaseIDContainersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) WithContext(ctx context.Context) *GetReleasesReleaseIDContainersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) WithHTTPClient(client *http.Client) *GetReleasesReleaseIDContainersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) WithPage(page *int64) *GetReleasesReleaseIDContainersParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) SetPage(page *int64) {
	o.Page = page
}

// WithReleaseID adds the releaseID to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) WithReleaseID(releaseID int64) *GetReleasesReleaseIDContainersParams {
	o.SetReleaseID(releaseID)
	return o
}

// SetReleaseID adds the releaseId to the get releases release ID containers params
func (o *GetReleasesReleaseIDContainersParams) SetReleaseID(releaseID int64) {
	o.ReleaseID = releaseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReleasesReleaseIDContainersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	// path param release_id
	if err := r.SetPathParam("release_id", swag.FormatInt64(o.ReleaseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
