// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetIntrusionDetectionReportsIDParams creates a new GetIntrusionDetectionReportsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIntrusionDetectionReportsIDParams() *GetIntrusionDetectionReportsIDParams {
	return &GetIntrusionDetectionReportsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIntrusionDetectionReportsIDParamsWithTimeout creates a new GetIntrusionDetectionReportsIDParams object
// with the ability to set a timeout on a request.
func NewGetIntrusionDetectionReportsIDParamsWithTimeout(timeout time.Duration) *GetIntrusionDetectionReportsIDParams {
	return &GetIntrusionDetectionReportsIDParams{
		timeout: timeout,
	}
}

// NewGetIntrusionDetectionReportsIDParamsWithContext creates a new GetIntrusionDetectionReportsIDParams object
// with the ability to set a context for a request.
func NewGetIntrusionDetectionReportsIDParamsWithContext(ctx context.Context) *GetIntrusionDetectionReportsIDParams {
	return &GetIntrusionDetectionReportsIDParams{
		Context: ctx,
	}
}

// NewGetIntrusionDetectionReportsIDParamsWithHTTPClient creates a new GetIntrusionDetectionReportsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIntrusionDetectionReportsIDParamsWithHTTPClient(client *http.Client) *GetIntrusionDetectionReportsIDParams {
	return &GetIntrusionDetectionReportsIDParams{
		HTTPClient: client,
	}
}

/* GetIntrusionDetectionReportsIDParams contains all the parameters to send to the API endpoint
   for the get intrusion detection reports ID operation.

   Typically these are written to a http.Request.
*/
type GetIntrusionDetectionReportsIDParams struct {

	/* ID.

	   id
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get intrusion detection reports ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIntrusionDetectionReportsIDParams) WithDefaults() *GetIntrusionDetectionReportsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get intrusion detection reports ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIntrusionDetectionReportsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) WithTimeout(timeout time.Duration) *GetIntrusionDetectionReportsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) WithContext(ctx context.Context) *GetIntrusionDetectionReportsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) WithHTTPClient(client *http.Client) *GetIntrusionDetectionReportsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) WithID(id int64) *GetIntrusionDetectionReportsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get intrusion detection reports ID params
func (o *GetIntrusionDetectionReportsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetIntrusionDetectionReportsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
