// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetAccountsAccountIDActivityReportsReader is a Reader for the GetAccountsAccountIDActivityReports structure.
type GetAccountsAccountIDActivityReportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountsAccountIDActivityReportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountsAccountIDActivityReportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAccountsAccountIDActivityReportsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAccountsAccountIDActivityReportsOK creates a GetAccountsAccountIDActivityReportsOK with default headers values
func NewGetAccountsAccountIDActivityReportsOK() *GetAccountsAccountIDActivityReportsOK {
	return &GetAccountsAccountIDActivityReportsOK{}
}

/*GetAccountsAccountIDActivityReportsOK handles this case with default header values.

successful
*/
type GetAccountsAccountIDActivityReportsOK struct {
	Payload *models.InlineResponse2002
}

func (o *GetAccountsAccountIDActivityReportsOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{account_id}/activity_reports][%d] getAccountsAccountIdActivityReportsOK  %+v", 200, o.Payload)
}

func (o *GetAccountsAccountIDActivityReportsOK) GetPayload() *models.InlineResponse2002 {
	return o.Payload
}

func (o *GetAccountsAccountIDActivityReportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse2002)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountsAccountIDActivityReportsDefault creates a GetAccountsAccountIDActivityReportsDefault with default headers values
func NewGetAccountsAccountIDActivityReportsDefault(code int) *GetAccountsAccountIDActivityReportsDefault {
	return &GetAccountsAccountIDActivityReportsDefault{
		_statusCode: code,
	}
}

/*GetAccountsAccountIDActivityReportsDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetAccountsAccountIDActivityReportsDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get accounts account ID activity reports default response
func (o *GetAccountsAccountIDActivityReportsDefault) Code() int {
	return o._statusCode
}

func (o *GetAccountsAccountIDActivityReportsDefault) Error() string {
	return fmt.Sprintf("[GET /accounts/{account_id}/activity_reports][%d] GetAccountsAccountIDActivityReports default  %+v", o._statusCode, o.Payload)
}

func (o *GetAccountsAccountIDActivityReportsDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetAccountsAccountIDActivityReportsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
