// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetDatabasesDatabaseIDDatabaseCredentialsReader is a Reader for the GetDatabasesDatabaseIDDatabaseCredentials structure.
type GetDatabasesDatabaseIDDatabaseCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDatabasesDatabaseIDDatabaseCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDatabasesDatabaseIDDatabaseCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDatabasesDatabaseIDDatabaseCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDatabasesDatabaseIDDatabaseCredentialsOK creates a GetDatabasesDatabaseIDDatabaseCredentialsOK with default headers values
func NewGetDatabasesDatabaseIDDatabaseCredentialsOK() *GetDatabasesDatabaseIDDatabaseCredentialsOK {
	return &GetDatabasesDatabaseIDDatabaseCredentialsOK{}
}

/*GetDatabasesDatabaseIDDatabaseCredentialsOK handles this case with default header values.

successful
*/
type GetDatabasesDatabaseIDDatabaseCredentialsOK struct {
	Payload *models.InlineResponse20010
}

func (o *GetDatabasesDatabaseIDDatabaseCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /databases/{database_id}/database_credentials][%d] getDatabasesDatabaseIdDatabaseCredentialsOK  %+v", 200, o.Payload)
}

func (o *GetDatabasesDatabaseIDDatabaseCredentialsOK) GetPayload() *models.InlineResponse20010 {
	return o.Payload
}

func (o *GetDatabasesDatabaseIDDatabaseCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20010)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatabasesDatabaseIDDatabaseCredentialsDefault creates a GetDatabasesDatabaseIDDatabaseCredentialsDefault with default headers values
func NewGetDatabasesDatabaseIDDatabaseCredentialsDefault(code int) *GetDatabasesDatabaseIDDatabaseCredentialsDefault {
	return &GetDatabasesDatabaseIDDatabaseCredentialsDefault{
		_statusCode: code,
	}
}

/*GetDatabasesDatabaseIDDatabaseCredentialsDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetDatabasesDatabaseIDDatabaseCredentialsDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get databases database ID database credentials default response
func (o *GetDatabasesDatabaseIDDatabaseCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *GetDatabasesDatabaseIDDatabaseCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /databases/{database_id}/database_credentials][%d] GetDatabasesDatabaseIDDatabaseCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *GetDatabasesDatabaseIDDatabaseCredentialsDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetDatabasesDatabaseIDDatabaseCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
