// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetIntrusionDetectionReportsIDReader is a Reader for the GetIntrusionDetectionReportsID structure.
type GetIntrusionDetectionReportsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIntrusionDetectionReportsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIntrusionDetectionReportsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetIntrusionDetectionReportsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetIntrusionDetectionReportsIDOK creates a GetIntrusionDetectionReportsIDOK with default headers values
func NewGetIntrusionDetectionReportsIDOK() *GetIntrusionDetectionReportsIDOK {
	return &GetIntrusionDetectionReportsIDOK{}
}

/*GetIntrusionDetectionReportsIDOK handles this case with default header values.

successful
*/
type GetIntrusionDetectionReportsIDOK struct {
	Payload *models.InlineResponse20027
}

func (o *GetIntrusionDetectionReportsIDOK) Error() string {
	return fmt.Sprintf("[GET /intrusion_detection_reports/{id}][%d] getIntrusionDetectionReportsIdOK  %+v", 200, o.Payload)
}

func (o *GetIntrusionDetectionReportsIDOK) GetPayload() *models.InlineResponse20027 {
	return o.Payload
}

func (o *GetIntrusionDetectionReportsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20027)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIntrusionDetectionReportsIDDefault creates a GetIntrusionDetectionReportsIDDefault with default headers values
func NewGetIntrusionDetectionReportsIDDefault(code int) *GetIntrusionDetectionReportsIDDefault {
	return &GetIntrusionDetectionReportsIDDefault{
		_statusCode: code,
	}
}

/*GetIntrusionDetectionReportsIDDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetIntrusionDetectionReportsIDDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get intrusion detection reports ID default response
func (o *GetIntrusionDetectionReportsIDDefault) Code() int {
	return o._statusCode
}

func (o *GetIntrusionDetectionReportsIDDefault) Error() string {
	return fmt.Sprintf("[GET /intrusion_detection_reports/{id}][%d] GetIntrusionDetectionReportsID default  %+v", o._statusCode, o.Payload)
}

func (o *GetIntrusionDetectionReportsIDDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetIntrusionDetectionReportsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
