// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDatabasesDatabaseIDDependentsParams creates a new GetDatabasesDatabaseIDDependentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDatabasesDatabaseIDDependentsParams() *GetDatabasesDatabaseIDDependentsParams {
	return &GetDatabasesDatabaseIDDependentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDatabasesDatabaseIDDependentsParamsWithTimeout creates a new GetDatabasesDatabaseIDDependentsParams object
// with the ability to set a timeout on a request.
func NewGetDatabasesDatabaseIDDependentsParamsWithTimeout(timeout time.Duration) *GetDatabasesDatabaseIDDependentsParams {
	return &GetDatabasesDatabaseIDDependentsParams{
		timeout: timeout,
	}
}

// NewGetDatabasesDatabaseIDDependentsParamsWithContext creates a new GetDatabasesDatabaseIDDependentsParams object
// with the ability to set a context for a request.
func NewGetDatabasesDatabaseIDDependentsParamsWithContext(ctx context.Context) *GetDatabasesDatabaseIDDependentsParams {
	return &GetDatabasesDatabaseIDDependentsParams{
		Context: ctx,
	}
}

// NewGetDatabasesDatabaseIDDependentsParamsWithHTTPClient creates a new GetDatabasesDatabaseIDDependentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDatabasesDatabaseIDDependentsParamsWithHTTPClient(client *http.Client) *GetDatabasesDatabaseIDDependentsParams {
	return &GetDatabasesDatabaseIDDependentsParams{
		HTTPClient: client,
	}
}

/* GetDatabasesDatabaseIDDependentsParams contains all the parameters to send to the API endpoint
   for the get databases database ID dependents operation.

   Typically these are written to a http.Request.
*/
type GetDatabasesDatabaseIDDependentsParams struct {

	/* DatabaseID.

	   database_id
	*/
	DatabaseID int64

	/* Page.

	   current page of results for pagination
	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get databases database ID dependents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDatabasesDatabaseIDDependentsParams) WithDefaults() *GetDatabasesDatabaseIDDependentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get databases database ID dependents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDatabasesDatabaseIDDependentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) WithTimeout(timeout time.Duration) *GetDatabasesDatabaseIDDependentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) WithContext(ctx context.Context) *GetDatabasesDatabaseIDDependentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) WithHTTPClient(client *http.Client) *GetDatabasesDatabaseIDDependentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDatabaseID adds the databaseID to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) WithDatabaseID(databaseID int64) *GetDatabasesDatabaseIDDependentsParams {
	o.SetDatabaseID(databaseID)
	return o
}

// SetDatabaseID adds the databaseId to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) SetDatabaseID(databaseID int64) {
	o.DatabaseID = databaseID
}

// WithPage adds the page to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) WithPage(page *int64) *GetDatabasesDatabaseIDDependentsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get databases database ID dependents params
func (o *GetDatabasesDatabaseIDDependentsParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetDatabasesDatabaseIDDependentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param database_id
	if err := r.SetPathParam("database_id", swag.FormatInt64(o.DatabaseID)); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
