// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/reggregory/go-deploy/models"
)

// GetDatabaseImagesReader is a Reader for the GetDatabaseImages structure.
type GetDatabaseImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDatabaseImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDatabaseImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDatabaseImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDatabaseImagesOK creates a GetDatabaseImagesOK with default headers values
func NewGetDatabaseImagesOK() *GetDatabaseImagesOK {
	return &GetDatabaseImagesOK{}
}

/*GetDatabaseImagesOK handles this case with default header values.

successful
*/
type GetDatabaseImagesOK struct {
	Payload *models.InlineResponse20013
}

func (o *GetDatabaseImagesOK) Error() string {
	return fmt.Sprintf("[GET /database_images][%d] getDatabaseImagesOK  %+v", 200, o.Payload)
}

func (o *GetDatabaseImagesOK) GetPayload() *models.InlineResponse20013 {
	return o.Payload
}

func (o *GetDatabaseImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20013)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatabaseImagesDefault creates a GetDatabaseImagesDefault with default headers values
func NewGetDatabaseImagesDefault(code int) *GetDatabaseImagesDefault {
	return &GetDatabaseImagesDefault{
		_statusCode: code,
	}
}

/*GetDatabaseImagesDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetDatabaseImagesDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get database images default response
func (o *GetDatabaseImagesDefault) Code() int {
	return o._statusCode
}

func (o *GetDatabaseImagesDefault) Error() string {
	return fmt.Sprintf("[GET /database_images][%d] GetDatabaseImages default  %+v", o._statusCode, o.Payload)
}

func (o *GetDatabaseImagesDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetDatabaseImagesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
