// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetBackupsBackupIDCopiesReader is a Reader for the GetBackupsBackupIDCopies structure.
type GetBackupsBackupIDCopiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBackupsBackupIDCopiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBackupsBackupIDCopiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetBackupsBackupIDCopiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBackupsBackupIDCopiesOK creates a GetBackupsBackupIDCopiesOK with default headers values
func NewGetBackupsBackupIDCopiesOK() *GetBackupsBackupIDCopiesOK {
	return &GetBackupsBackupIDCopiesOK{}
}

/*GetBackupsBackupIDCopiesOK handles this case with default header values.

successful
*/
type GetBackupsBackupIDCopiesOK struct {
	Payload *models.InlineResponse2006
}

func (o *GetBackupsBackupIDCopiesOK) Error() string {
	return fmt.Sprintf("[GET /backups/{backup_id}/copies][%d] getBackupsBackupIdCopiesOK  %+v", 200, o.Payload)
}

func (o *GetBackupsBackupIDCopiesOK) GetPayload() *models.InlineResponse2006 {
	return o.Payload
}

func (o *GetBackupsBackupIDCopiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse2006)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupsBackupIDCopiesDefault creates a GetBackupsBackupIDCopiesDefault with default headers values
func NewGetBackupsBackupIDCopiesDefault(code int) *GetBackupsBackupIDCopiesDefault {
	return &GetBackupsBackupIDCopiesDefault{
		_statusCode: code,
	}
}

/*GetBackupsBackupIDCopiesDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetBackupsBackupIDCopiesDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get backups backup ID copies default response
func (o *GetBackupsBackupIDCopiesDefault) Code() int {
	return o._statusCode
}

func (o *GetBackupsBackupIDCopiesDefault) Error() string {
	return fmt.Sprintf("[GET /backups/{backup_id}/copies][%d] GetBackupsBackupIDCopies default  %+v", o._statusCode, o.Payload)
}

func (o *GetBackupsBackupIDCopiesDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetBackupsBackupIDCopiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
