// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAppsAppIDVhostsParams creates a new GetAppsAppIDVhostsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAppsAppIDVhostsParams() *GetAppsAppIDVhostsParams {
	return &GetAppsAppIDVhostsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppsAppIDVhostsParamsWithTimeout creates a new GetAppsAppIDVhostsParams object
// with the ability to set a timeout on a request.
func NewGetAppsAppIDVhostsParamsWithTimeout(timeout time.Duration) *GetAppsAppIDVhostsParams {
	return &GetAppsAppIDVhostsParams{
		timeout: timeout,
	}
}

// NewGetAppsAppIDVhostsParamsWithContext creates a new GetAppsAppIDVhostsParams object
// with the ability to set a context for a request.
func NewGetAppsAppIDVhostsParamsWithContext(ctx context.Context) *GetAppsAppIDVhostsParams {
	return &GetAppsAppIDVhostsParams{
		Context: ctx,
	}
}

// NewGetAppsAppIDVhostsParamsWithHTTPClient creates a new GetAppsAppIDVhostsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAppsAppIDVhostsParamsWithHTTPClient(client *http.Client) *GetAppsAppIDVhostsParams {
	return &GetAppsAppIDVhostsParams{
		HTTPClient: client,
	}
}

/* GetAppsAppIDVhostsParams contains all the parameters to send to the API endpoint
   for the get apps app ID vhosts operation.

   Typically these are written to a http.Request.
*/
type GetAppsAppIDVhostsParams struct {

	/* AppID.

	   app_id
	*/
	AppID int64

	/* Page.

	   current page of results for pagination
	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get apps app ID vhosts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAppsAppIDVhostsParams) WithDefaults() *GetAppsAppIDVhostsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get apps app ID vhosts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAppsAppIDVhostsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) WithTimeout(timeout time.Duration) *GetAppsAppIDVhostsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) WithContext(ctx context.Context) *GetAppsAppIDVhostsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) WithHTTPClient(client *http.Client) *GetAppsAppIDVhostsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) WithAppID(appID int64) *GetAppsAppIDVhostsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) SetAppID(appID int64) {
	o.AppID = appID
}

// WithPage adds the page to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) WithPage(page *int64) *GetAppsAppIDVhostsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get apps app ID vhosts params
func (o *GetAppsAppIDVhostsParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppsAppIDVhostsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_id
	if err := r.SetPathParam("app_id", swag.FormatInt64(o.AppID)); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
