// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAccountsAccountIDBackupRetentionPoliciesParams creates a new GetAccountsAccountIDBackupRetentionPoliciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountsAccountIDBackupRetentionPoliciesParams() *GetAccountsAccountIDBackupRetentionPoliciesParams {
	return &GetAccountsAccountIDBackupRetentionPoliciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountsAccountIDBackupRetentionPoliciesParamsWithTimeout creates a new GetAccountsAccountIDBackupRetentionPoliciesParams object
// with the ability to set a timeout on a request.
func NewGetAccountsAccountIDBackupRetentionPoliciesParamsWithTimeout(timeout time.Duration) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	return &GetAccountsAccountIDBackupRetentionPoliciesParams{
		timeout: timeout,
	}
}

// NewGetAccountsAccountIDBackupRetentionPoliciesParamsWithContext creates a new GetAccountsAccountIDBackupRetentionPoliciesParams object
// with the ability to set a context for a request.
func NewGetAccountsAccountIDBackupRetentionPoliciesParamsWithContext(ctx context.Context) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	return &GetAccountsAccountIDBackupRetentionPoliciesParams{
		Context: ctx,
	}
}

// NewGetAccountsAccountIDBackupRetentionPoliciesParamsWithHTTPClient creates a new GetAccountsAccountIDBackupRetentionPoliciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountsAccountIDBackupRetentionPoliciesParamsWithHTTPClient(client *http.Client) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	return &GetAccountsAccountIDBackupRetentionPoliciesParams{
		HTTPClient: client,
	}
}

/* GetAccountsAccountIDBackupRetentionPoliciesParams contains all the parameters to send to the API endpoint
   for the get accounts account ID backup retention policies operation.

   Typically these are written to a http.Request.
*/
type GetAccountsAccountIDBackupRetentionPoliciesParams struct {

	/* AccountID.

	   account_id
	*/
	AccountID int64

	/* Page.

	   current page of results for pagination
	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get accounts account ID backup retention policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WithDefaults() *GetAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get accounts account ID backup retention policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WithTimeout(timeout time.Duration) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WithContext(ctx context.Context) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WithHTTPClient(client *http.Client) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WithAccountID(accountID int64) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) SetAccountID(accountID int64) {
	o.AccountID = accountID
}

// WithPage adds the page to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WithPage(page *int64) *GetAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get accounts account ID backup retention policies params
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountsAccountIDBackupRetentionPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", swag.FormatInt64(o.AccountID)); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
