// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetAppsAppIDImagesReader is a Reader for the GetAppsAppIDImages structure.
type GetAppsAppIDImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppsAppIDImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAppsAppIDImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAppsAppIDImagesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAppsAppIDImagesOK creates a GetAppsAppIDImagesOK with default headers values
func NewGetAppsAppIDImagesOK() *GetAppsAppIDImagesOK {
	return &GetAppsAppIDImagesOK{}
}

/*GetAppsAppIDImagesOK handles this case with default header values.

successful
*/
type GetAppsAppIDImagesOK struct {
	Payload *models.InlineResponse20022
}

func (o *GetAppsAppIDImagesOK) Error() string {
	return fmt.Sprintf("[GET /apps/{app_id}/images][%d] getAppsAppIdImagesOK  %+v", 200, o.Payload)
}

func (o *GetAppsAppIDImagesOK) GetPayload() *models.InlineResponse20022 {
	return o.Payload
}

func (o *GetAppsAppIDImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20022)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppsAppIDImagesDefault creates a GetAppsAppIDImagesDefault with default headers values
func NewGetAppsAppIDImagesDefault(code int) *GetAppsAppIDImagesDefault {
	return &GetAppsAppIDImagesDefault{
		_statusCode: code,
	}
}

/*GetAppsAppIDImagesDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetAppsAppIDImagesDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get apps app ID images default response
func (o *GetAppsAppIDImagesDefault) Code() int {
	return o._statusCode
}

func (o *GetAppsAppIDImagesDefault) Error() string {
	return fmt.Sprintf("[GET /apps/{app_id}/images][%d] GetAppsAppIDImages default  %+v", o._statusCode, o.Payload)
}

func (o *GetAppsAppIDImagesDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetAppsAppIDImagesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
