// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// GetConfigurationsIDReader is a Reader for the GetConfigurationsID structure.
type GetConfigurationsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigurationsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigurationsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetConfigurationsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetConfigurationsIDOK creates a GetConfigurationsIDOK with default headers values
func NewGetConfigurationsIDOK() *GetConfigurationsIDOK {
	return &GetConfigurationsIDOK{}
}

/*GetConfigurationsIDOK handles this case with default header values.

successful
*/
type GetConfigurationsIDOK struct {
	Payload *models.InlineResponse20011
}

func (o *GetConfigurationsIDOK) Error() string {
	return fmt.Sprintf("[GET /configurations/{id}][%d] getConfigurationsIdOK  %+v", 200, o.Payload)
}

func (o *GetConfigurationsIDOK) GetPayload() *models.InlineResponse20011 {
	return o.Payload
}

func (o *GetConfigurationsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20011)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigurationsIDDefault creates a GetConfigurationsIDDefault with default headers values
func NewGetConfigurationsIDDefault(code int) *GetConfigurationsIDDefault {
	return &GetConfigurationsIDDefault{
		_statusCode: code,
	}
}

/*GetConfigurationsIDDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type GetConfigurationsIDDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the get configurations ID default response
func (o *GetConfigurationsIDDefault) Code() int {
	return o._statusCode
}

func (o *GetConfigurationsIDDefault) Error() string {
	return fmt.Sprintf("[GET /configurations/{id}][%d] GetConfigurationsID default  %+v", o._statusCode, o.Payload)
}

func (o *GetConfigurationsIDDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *GetConfigurationsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
