// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// NewPatchOperationsIDParams creates a new PatchOperationsIDParams object
// with the default values initialized.
func NewPatchOperationsIDParams() *PatchOperationsIDParams {
	var ()
	return &PatchOperationsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchOperationsIDParamsWithTimeout creates a new PatchOperationsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchOperationsIDParamsWithTimeout(timeout time.Duration) *PatchOperationsIDParams {
	var ()
	return &PatchOperationsIDParams{

		timeout: timeout,
	}
}

// NewPatchOperationsIDParamsWithContext creates a new PatchOperationsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchOperationsIDParamsWithContext(ctx context.Context) *PatchOperationsIDParams {
	var ()
	return &PatchOperationsIDParams{

		Context: ctx,
	}
}

// NewPatchOperationsIDParamsWithHTTPClient creates a new PatchOperationsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchOperationsIDParamsWithHTTPClient(client *http.Client) *PatchOperationsIDParams {
	var ()
	return &PatchOperationsIDParams{
		HTTPClient: client,
	}
}

/*PatchOperationsIDParams contains all the parameters to send to the API endpoint
for the patch operations ID operation typically these are written to a http.Request
*/
type PatchOperationsIDParams struct {

	/*AppRequest*/
	AppRequest *models.AppRequest20
	/*ID
	  id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch operations ID params
func (o *PatchOperationsIDParams) WithTimeout(timeout time.Duration) *PatchOperationsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch operations ID params
func (o *PatchOperationsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch operations ID params
func (o *PatchOperationsIDParams) WithContext(ctx context.Context) *PatchOperationsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch operations ID params
func (o *PatchOperationsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch operations ID params
func (o *PatchOperationsIDParams) WithHTTPClient(client *http.Client) *PatchOperationsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch operations ID params
func (o *PatchOperationsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppRequest adds the appRequest to the patch operations ID params
func (o *PatchOperationsIDParams) WithAppRequest(appRequest *models.AppRequest20) *PatchOperationsIDParams {
	o.SetAppRequest(appRequest)
	return o
}

// SetAppRequest adds the appRequest to the patch operations ID params
func (o *PatchOperationsIDParams) SetAppRequest(appRequest *models.AppRequest20) {
	o.AppRequest = appRequest
}

// WithID adds the id to the patch operations ID params
func (o *PatchOperationsIDParams) WithID(id int64) *PatchOperationsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch operations ID params
func (o *PatchOperationsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchOperationsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AppRequest != nil {
		if err := r.SetBodyParam(o.AppRequest); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
