// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// NewPostAppsAppIDOperationsParams creates a new PostAppsAppIDOperationsParams object
// with the default values initialized.
func NewPostAppsAppIDOperationsParams() *PostAppsAppIDOperationsParams {
	var ()
	return &PostAppsAppIDOperationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAppsAppIDOperationsParamsWithTimeout creates a new PostAppsAppIDOperationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAppsAppIDOperationsParamsWithTimeout(timeout time.Duration) *PostAppsAppIDOperationsParams {
	var ()
	return &PostAppsAppIDOperationsParams{

		timeout: timeout,
	}
}

// NewPostAppsAppIDOperationsParamsWithContext creates a new PostAppsAppIDOperationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAppsAppIDOperationsParamsWithContext(ctx context.Context) *PostAppsAppIDOperationsParams {
	var ()
	return &PostAppsAppIDOperationsParams{

		Context: ctx,
	}
}

// NewPostAppsAppIDOperationsParamsWithHTTPClient creates a new PostAppsAppIDOperationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAppsAppIDOperationsParamsWithHTTPClient(client *http.Client) *PostAppsAppIDOperationsParams {
	var ()
	return &PostAppsAppIDOperationsParams{
		HTTPClient: client,
	}
}

/*PostAppsAppIDOperationsParams contains all the parameters to send to the API endpoint
for the post apps app ID operations operation typically these are written to a http.Request
*/
type PostAppsAppIDOperationsParams struct {

	/*AppID
	  app_id

	*/
	AppID int64
	/*AppRequest*/
	AppRequest *models.AppRequest22

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) WithTimeout(timeout time.Duration) *PostAppsAppIDOperationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) WithContext(ctx context.Context) *PostAppsAppIDOperationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) WithHTTPClient(client *http.Client) *PostAppsAppIDOperationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) WithAppID(appID int64) *PostAppsAppIDOperationsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) SetAppID(appID int64) {
	o.AppID = appID
}

// WithAppRequest adds the appRequest to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) WithAppRequest(appRequest *models.AppRequest22) *PostAppsAppIDOperationsParams {
	o.SetAppRequest(appRequest)
	return o
}

// SetAppRequest adds the appRequest to the post apps app ID operations params
func (o *PostAppsAppIDOperationsParams) SetAppRequest(appRequest *models.AppRequest22) {
	o.AppRequest = appRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostAppsAppIDOperationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_id
	if err := r.SetPathParam("app_id", swag.FormatInt64(o.AppID)); err != nil {
		return err
	}

	if o.AppRequest != nil {
		if err := r.SetBodyParam(o.AppRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
