// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/reggregory/go-deploy/models"
)

// PostClaimsTypeReader is a Reader for the PostClaimsType structure.
type PostClaimsTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostClaimsTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostClaimsTypeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostClaimsTypeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostClaimsTypeNoContent creates a PostClaimsTypeNoContent with default headers values
func NewPostClaimsTypeNoContent() *PostClaimsTypeNoContent {
	return &PostClaimsTypeNoContent{}
}

/*PostClaimsTypeNoContent handles this case with default header values.

successful
*/
type PostClaimsTypeNoContent struct {
}

func (o *PostClaimsTypeNoContent) Error() string {
	return fmt.Sprintf("[POST /claims/{type}][%d] postClaimsTypeNoContent ", 204)
}

func (o *PostClaimsTypeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostClaimsTypeDefault creates a PostClaimsTypeDefault with default headers values
func NewPostClaimsTypeDefault(code int) *PostClaimsTypeDefault {
	return &PostClaimsTypeDefault{
		_statusCode: code,
	}
}

/*PostClaimsTypeDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type PostClaimsTypeDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the post claims type default response
func (o *PostClaimsTypeDefault) Code() int {
	return o._statusCode
}

func (o *PostClaimsTypeDefault) Error() string {
	return fmt.Sprintf("[POST /claims/{type}][%d] PostClaimsType default  %+v", o._statusCode, o.Payload)
}

func (o *PostClaimsTypeDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *PostClaimsTypeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
