// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/reggregory/go-deploy/models"
)

// PostMetricDrainsMetricDrainIDOperationsReader is a Reader for the PostMetricDrainsMetricDrainIDOperations structure.
type PostMetricDrainsMetricDrainIDOperationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMetricDrainsMetricDrainIDOperationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostMetricDrainsMetricDrainIDOperationsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostMetricDrainsMetricDrainIDOperationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostMetricDrainsMetricDrainIDOperationsCreated creates a PostMetricDrainsMetricDrainIDOperationsCreated with default headers values
func NewPostMetricDrainsMetricDrainIDOperationsCreated() *PostMetricDrainsMetricDrainIDOperationsCreated {
	return &PostMetricDrainsMetricDrainIDOperationsCreated{}
}

/*PostMetricDrainsMetricDrainIDOperationsCreated handles this case with default header values.

successful
*/
type PostMetricDrainsMetricDrainIDOperationsCreated struct {
	Payload *models.InlineResponse20028
}

func (o *PostMetricDrainsMetricDrainIDOperationsCreated) Error() string {
	return fmt.Sprintf("[POST /metric_drains/{metric_drain_id}/operations][%d] postMetricDrainsMetricDrainIdOperationsCreated  %+v", 201, o.Payload)
}

func (o *PostMetricDrainsMetricDrainIDOperationsCreated) GetPayload() *models.InlineResponse20028 {
	return o.Payload
}

func (o *PostMetricDrainsMetricDrainIDOperationsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse20028)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostMetricDrainsMetricDrainIDOperationsDefault creates a PostMetricDrainsMetricDrainIDOperationsDefault with default headers values
func NewPostMetricDrainsMetricDrainIDOperationsDefault(code int) *PostMetricDrainsMetricDrainIDOperationsDefault {
	return &PostMetricDrainsMetricDrainIDOperationsDefault{
		_statusCode: code,
	}
}

/*PostMetricDrainsMetricDrainIDOperationsDefault handles this case with default header values.

Error response. Often a 4xx or 5xx status code
*/
type PostMetricDrainsMetricDrainIDOperationsDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the post metric drains metric drain ID operations default response
func (o *PostMetricDrainsMetricDrainIDOperationsDefault) Code() int {
	return o._statusCode
}

func (o *PostMetricDrainsMetricDrainIDOperationsDefault) Error() string {
	return fmt.Sprintf("[POST /metric_drains/{metric_drain_id}/operations][%d] PostMetricDrainsMetricDrainIDOperations default  %+v", o._statusCode, o.Payload)
}

func (o *PostMetricDrainsMetricDrainIDOperationsDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *PostMetricDrainsMetricDrainIDOperationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
