// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/aptible/go-deploy/models"
)

// NewPostDatabasesDatabaseIDConfigurationsParams creates a new PostDatabasesDatabaseIDConfigurationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDatabasesDatabaseIDConfigurationsParams() *PostDatabasesDatabaseIDConfigurationsParams {
	return &PostDatabasesDatabaseIDConfigurationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDatabasesDatabaseIDConfigurationsParamsWithTimeout creates a new PostDatabasesDatabaseIDConfigurationsParams object
// with the ability to set a timeout on a request.
func NewPostDatabasesDatabaseIDConfigurationsParamsWithTimeout(timeout time.Duration) *PostDatabasesDatabaseIDConfigurationsParams {
	return &PostDatabasesDatabaseIDConfigurationsParams{
		timeout: timeout,
	}
}

// NewPostDatabasesDatabaseIDConfigurationsParamsWithContext creates a new PostDatabasesDatabaseIDConfigurationsParams object
// with the ability to set a context for a request.
func NewPostDatabasesDatabaseIDConfigurationsParamsWithContext(ctx context.Context) *PostDatabasesDatabaseIDConfigurationsParams {
	return &PostDatabasesDatabaseIDConfigurationsParams{
		Context: ctx,
	}
}

// NewPostDatabasesDatabaseIDConfigurationsParamsWithHTTPClient creates a new PostDatabasesDatabaseIDConfigurationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDatabasesDatabaseIDConfigurationsParamsWithHTTPClient(client *http.Client) *PostDatabasesDatabaseIDConfigurationsParams {
	return &PostDatabasesDatabaseIDConfigurationsParams{
		HTTPClient: client,
	}
}

/* PostDatabasesDatabaseIDConfigurationsParams contains all the parameters to send to the API endpoint
   for the post databases database ID configurations operation.

   Typically these are written to a http.Request.
*/
type PostDatabasesDatabaseIDConfigurationsParams struct {

	// AppRequest.
	AppRequest *models.AppRequest12

	/* DatabaseID.

	   database_id
	*/
	DatabaseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post databases database ID configurations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDatabasesDatabaseIDConfigurationsParams) WithDefaults() *PostDatabasesDatabaseIDConfigurationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post databases database ID configurations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDatabasesDatabaseIDConfigurationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) WithTimeout(timeout time.Duration) *PostDatabasesDatabaseIDConfigurationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) WithContext(ctx context.Context) *PostDatabasesDatabaseIDConfigurationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) WithHTTPClient(client *http.Client) *PostDatabasesDatabaseIDConfigurationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppRequest adds the appRequest to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) WithAppRequest(appRequest *models.AppRequest12) *PostDatabasesDatabaseIDConfigurationsParams {
	o.SetAppRequest(appRequest)
	return o
}

// SetAppRequest adds the appRequest to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) SetAppRequest(appRequest *models.AppRequest12) {
	o.AppRequest = appRequest
}

// WithDatabaseID adds the databaseID to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) WithDatabaseID(databaseID int64) *PostDatabasesDatabaseIDConfigurationsParams {
	o.SetDatabaseID(databaseID)
	return o
}

// SetDatabaseID adds the databaseId to the post databases database ID configurations params
func (o *PostDatabasesDatabaseIDConfigurationsParams) SetDatabaseID(databaseID int64) {
	o.DatabaseID = databaseID
}

// WriteToRequest writes these params to a swagger request
func (o *PostDatabasesDatabaseIDConfigurationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.AppRequest != nil {
		if err := r.SetBodyParam(o.AppRequest); err != nil {
			return err
		}
	}

	// path param database_id
	if err := r.SetPathParam("database_id", swag.FormatInt64(o.DatabaseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
