// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aptible/go-deploy/models"
)

// NewPostAccountsAccountIDBackupRetentionPoliciesParams creates a new PostAccountsAccountIDBackupRetentionPoliciesParams object
// with the default values initialized.
func NewPostAccountsAccountIDBackupRetentionPoliciesParams() *PostAccountsAccountIDBackupRetentionPoliciesParams {
	var ()
	return &PostAccountsAccountIDBackupRetentionPoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccountsAccountIDBackupRetentionPoliciesParamsWithTimeout creates a new PostAccountsAccountIDBackupRetentionPoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAccountsAccountIDBackupRetentionPoliciesParamsWithTimeout(timeout time.Duration) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	var ()
	return &PostAccountsAccountIDBackupRetentionPoliciesParams{

		timeout: timeout,
	}
}

// NewPostAccountsAccountIDBackupRetentionPoliciesParamsWithContext creates a new PostAccountsAccountIDBackupRetentionPoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAccountsAccountIDBackupRetentionPoliciesParamsWithContext(ctx context.Context) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	var ()
	return &PostAccountsAccountIDBackupRetentionPoliciesParams{

		Context: ctx,
	}
}

// NewPostAccountsAccountIDBackupRetentionPoliciesParamsWithHTTPClient creates a new PostAccountsAccountIDBackupRetentionPoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAccountsAccountIDBackupRetentionPoliciesParamsWithHTTPClient(client *http.Client) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	var ()
	return &PostAccountsAccountIDBackupRetentionPoliciesParams{
		HTTPClient: client,
	}
}

/*PostAccountsAccountIDBackupRetentionPoliciesParams contains all the parameters to send to the API endpoint
for the post accounts account ID backup retention policies operation typically these are written to a http.Request
*/
type PostAccountsAccountIDBackupRetentionPoliciesParams struct {

	/*AccountID
	  account_id

	*/
	AccountID int64
	/*AppRequest*/
	AppRequest *models.AppRequest4

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) WithTimeout(timeout time.Duration) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) WithContext(ctx context.Context) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) WithHTTPClient(client *http.Client) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) WithAccountID(accountID int64) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) SetAccountID(accountID int64) {
	o.AccountID = accountID
}

// WithAppRequest adds the appRequest to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) WithAppRequest(appRequest *models.AppRequest4) *PostAccountsAccountIDBackupRetentionPoliciesParams {
	o.SetAppRequest(appRequest)
	return o
}

// SetAppRequest adds the appRequest to the post accounts account ID backup retention policies params
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) SetAppRequest(appRequest *models.AppRequest4) {
	o.AppRequest = appRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccountsAccountIDBackupRetentionPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", swag.FormatInt64(o.AccountID)); err != nil {
		return err
	}

	if o.AppRequest != nil {
		if err := r.SetBodyParam(o.AppRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
