// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aptible/go-deploy/models"
)

// PutLogDrainsIDReader is a Reader for the PutLogDrainsID structure.
type PutLogDrainsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutLogDrainsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutLogDrainsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutLogDrainsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutLogDrainsIDOK creates a PutLogDrainsIDOK with default headers values
func NewPutLogDrainsIDOK() *PutLogDrainsIDOK {
	return &PutLogDrainsIDOK{}
}

/* PutLogDrainsIDOK describes a response with status code 200, with default header values.

successful
*/
type PutLogDrainsIDOK struct {
}

func (o *PutLogDrainsIDOK) Error() string {
	return fmt.Sprintf("[PUT /log_drains/{id}][%d] putLogDrainsIdOK ", 200)
}

func (o *PutLogDrainsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutLogDrainsIDDefault creates a PutLogDrainsIDDefault with default headers values
func NewPutLogDrainsIDDefault(code int) *PutLogDrainsIDDefault {
	return &PutLogDrainsIDDefault{
		_statusCode: code,
	}
}

/* PutLogDrainsIDDefault describes a response with status code -1, with default header values.

Error response. Often a 4xx or 5xx status code
*/
type PutLogDrainsIDDefault struct {
	_statusCode int

	Payload *models.InlineResponseDefault
}

// Code gets the status code for the put log drains ID default response
func (o *PutLogDrainsIDDefault) Code() int {
	return o._statusCode
}

func (o *PutLogDrainsIDDefault) Error() string {
	return fmt.Sprintf("[PUT /log_drains/{id}][%d] PutLogDrainsID default  %+v", o._statusCode, o.Payload)
}
func (o *PutLogDrainsIDDefault) GetPayload() *models.InlineResponseDefault {
	return o.Payload
}

func (o *PutLogDrainsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponseDefault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
