// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/reggregory/go-deploy/models"
)

// NewPutOperationsIDParams creates a new PutOperationsIDParams object
// with the default values initialized.
func NewPutOperationsIDParams() *PutOperationsIDParams {
	var ()
	return &PutOperationsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutOperationsIDParamsWithTimeout creates a new PutOperationsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutOperationsIDParamsWithTimeout(timeout time.Duration) *PutOperationsIDParams {
	var ()
	return &PutOperationsIDParams{

		timeout: timeout,
	}
}

// NewPutOperationsIDParamsWithContext creates a new PutOperationsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutOperationsIDParamsWithContext(ctx context.Context) *PutOperationsIDParams {
	var ()
	return &PutOperationsIDParams{

		Context: ctx,
	}
}

// NewPutOperationsIDParamsWithHTTPClient creates a new PutOperationsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutOperationsIDParamsWithHTTPClient(client *http.Client) *PutOperationsIDParams {
	var ()
	return &PutOperationsIDParams{
		HTTPClient: client,
	}
}

/*PutOperationsIDParams contains all the parameters to send to the API endpoint
for the put operations ID operation typically these are written to a http.Request
*/
type PutOperationsIDParams struct {

	/*AppRequest*/
	AppRequest *models.AppRequest19
	/*ID
	  id

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put operations ID params
func (o *PutOperationsIDParams) WithTimeout(timeout time.Duration) *PutOperationsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put operations ID params
func (o *PutOperationsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put operations ID params
func (o *PutOperationsIDParams) WithContext(ctx context.Context) *PutOperationsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put operations ID params
func (o *PutOperationsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put operations ID params
func (o *PutOperationsIDParams) WithHTTPClient(client *http.Client) *PutOperationsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put operations ID params
func (o *PutOperationsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppRequest adds the appRequest to the put operations ID params
func (o *PutOperationsIDParams) WithAppRequest(appRequest *models.AppRequest19) *PutOperationsIDParams {
	o.SetAppRequest(appRequest)
	return o
}

// SetAppRequest adds the appRequest to the put operations ID params
func (o *PutOperationsIDParams) SetAppRequest(appRequest *models.AppRequest19) {
	o.AppRequest = appRequest
}

// WithID adds the id to the put operations ID params
func (o *PutOperationsIDParams) WithID(id int64) *PutOperationsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put operations ID params
func (o *PutOperationsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutOperationsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AppRequest != nil {
		if err := r.SetBodyParam(o.AppRequest); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
