on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

env:
  GOFLAGS: "-mod=vendor"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.13'

      - name: Setup
        run: |
          make tools
          go mod vendor

      - name: Code Lint
        run:  make lint

      - name: Code UnitTest
        run: make test

      - name: Generated Code is Current
        run: |
          make gen
          git diff --quiet
