// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AppRequest32 app request 32
// swagger:model app_request_32
type AppRequest32 struct {

	// command
	Command string `json:"command,omitempty"`

	// ssh public key
	// Required: true
	SSHPublicKey *string `json:"ssh_public_key"`
}

// Validate validates this app request 32
func (m *AppRequest32) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSSHPublicKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRequest32) validateSSHPublicKey(formats strfmt.Registry) error {

	if err := validate.Required("ssh_public_key", "body", m.SSHPublicKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppRequest32) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRequest32) UnmarshalBinary(b []byte) error {
	var res AppRequest32
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
