// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppRequest20 app request 20
//
// swagger:model app_request_20
type AppRequest20 struct {

	// cancelled
	Cancelled bool `json:"cancelled"`
}

// Validate validates this app request 20
func (m *AppRequest20) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app request 20 based on context it is used
func (m *AppRequest20) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppRequest20) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRequest20) UnmarshalBinary(b []byte) error {
	var res AppRequest20
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
