// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AppRequest13 app request 13
// swagger:model app_request_13
type AppRequest13 struct {

	// current configuration
	CurrentConfiguration int64 `json:"current_configuration,omitempty"`

	// initial continer size
	InitialContinerSize int64 `json:"initial_continer_size,omitempty"`

	// initial disk size
	InitialDiskSize int64 `json:"initial_disk_size,omitempty"`
}

// Validate validates this app request 13
func (m *AppRequest13) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppRequest13) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRequest13) UnmarshalBinary(b []byte) error {
	var res AppRequest13
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
