// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse20040Embedded inline response 200 40 embedded
// swagger:model inline_response_200_40__embedded
type InlineResponse20040Embedded struct {

	// vhosts
	Vhosts []*InlineResponse20040EmbeddedVhosts `json:"vhosts"`
}

// Validate validates this inline response 200 40 embedded
func (m *InlineResponse20040Embedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVhosts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20040Embedded) validateVhosts(formats strfmt.Registry) error {

	if swag.IsZero(m.Vhosts) { // not required
		return nil
	}

	for i := 0; i < len(m.Vhosts); i++ {
		if swag.IsZero(m.Vhosts[i]) { // not required
			continue
		}

		if m.Vhosts[i] != nil {
			if err := m.Vhosts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vhosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse20040Embedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse20040Embedded) UnmarshalBinary(b []byte) error {
	var res InlineResponse20040Embedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
