// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse20038EmbeddedAcmeConfiguration inline response 200 38 embedded acme configuration
// swagger:model inline_response_200_38__embedded_acme_configuration
type InlineResponse20038EmbeddedAcmeConfiguration struct {

	// challenges
	Challenges []*InlineResponse20038EmbeddedAcmeConfigurationChallenges `json:"challenges"`

	// names
	Names []string `json:"names"`
}

// Validate validates this inline response 200 38 embedded acme configuration
func (m *InlineResponse20038EmbeddedAcmeConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChallenges(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20038EmbeddedAcmeConfiguration) validateChallenges(formats strfmt.Registry) error {

	if swag.IsZero(m.Challenges) { // not required
		return nil
	}

	for i := 0; i < len(m.Challenges); i++ {
		if swag.IsZero(m.Challenges[i]) { // not required
			continue
		}

		if m.Challenges[i] != nil {
			if err := m.Challenges[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("challenges" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse20038EmbeddedAcmeConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse20038EmbeddedAcmeConfiguration) UnmarshalBinary(b []byte) error {
	var res InlineResponse20038EmbeddedAcmeConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
