// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InlineResponse20019Embedded inline response 200 19 embedded
//
// swagger:model inline_response_200_19__embedded
type InlineResponse20019Embedded struct {

	// ephemeral containers
	EphemeralContainers []*InlineResponse20019EmbeddedEphemeralContainers `json:"ephemeral_containers"`
}

// Validate validates this inline response 200 19 embedded
func (m *InlineResponse20019Embedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEphemeralContainers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20019Embedded) validateEphemeralContainers(formats strfmt.Registry) error {
	if swag.IsZero(m.EphemeralContainers) { // not required
		return nil
	}

	for i := 0; i < len(m.EphemeralContainers); i++ {
		if swag.IsZero(m.EphemeralContainers[i]) { // not required
			continue
		}

		if m.EphemeralContainers[i] != nil {
			if err := m.EphemeralContainers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ephemeral_containers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ephemeral_containers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inline response 200 19 embedded based on the context it is used
func (m *InlineResponse20019Embedded) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEphemeralContainers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20019Embedded) contextValidateEphemeralContainers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EphemeralContainers); i++ {

		if m.EphemeralContainers[i] != nil {
			if err := m.EphemeralContainers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ephemeral_containers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ephemeral_containers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse20019Embedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse20019Embedded) UnmarshalBinary(b []byte) error {
	var res InlineResponse20019Embedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
