// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse20024EmbeddedIntrusionDetectionReports inline response 200 24 embedded intrusion detection reports
// swagger:model inline_response_200_24__embedded_intrusion_detection_reports
type InlineResponse20024EmbeddedIntrusionDetectionReports struct {

	// resource type
	ResourceType string `json:"_type,omitempty"`

	// links
	Links *InlineResponse20024EmbeddedLinks `json:"_links,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// ends at
	EndsAt string `json:"ends_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// starts at
	StartsAt string `json:"starts_at,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this inline response 200 24 embedded intrusion detection reports
func (m *InlineResponse20024EmbeddedIntrusionDetectionReports) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20024EmbeddedIntrusionDetectionReports) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse20024EmbeddedIntrusionDetectionReports) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse20024EmbeddedIntrusionDetectionReports) UnmarshalBinary(b []byte) error {
	var res InlineResponse20024EmbeddedIntrusionDetectionReports
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
