// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// InlineResponse2006EmbeddedEmbedded inline response 200 6 embedded embedded
// swagger:model inline_response_200_6__embedded__embedded
type InlineResponse2006EmbeddedEmbedded struct {

	// copied from
	CopiedFrom interface{} `json:"copied_from,omitempty"`
}

// Validate validates this inline response 200 6 embedded embedded
func (m *InlineResponse2006EmbeddedEmbedded) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse2006EmbeddedEmbedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse2006EmbeddedEmbedded) UnmarshalBinary(b []byte) error {
	var res InlineResponse2006EmbeddedEmbedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
