// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse2006Embedded inline response 200 6 embedded
// swagger:model inline_response_200_6__embedded
type InlineResponse2006Embedded struct {

	// backups
	Backups []*InlineResponse2006EmbeddedBackups `json:"backups"`
}

// Validate validates this inline response 200 6 embedded
func (m *InlineResponse2006Embedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBackups(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse2006Embedded) validateBackups(formats strfmt.Registry) error {

	if swag.IsZero(m.Backups) { // not required
		return nil
	}

	for i := 0; i < len(m.Backups); i++ {
		if swag.IsZero(m.Backups[i]) { // not required
			continue
		}

		if m.Backups[i] != nil {
			if err := m.Backups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("backups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse2006Embedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse2006Embedded) UnmarshalBinary(b []byte) error {
	var res InlineResponse2006Embedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
