// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InlineResponse20026Embedded inline response 200 26 embedded
//
// swagger:model inline_response_200_26__embedded
type InlineResponse20026Embedded struct {

	// intrusion detection reports
	IntrusionDetectionReports []*InlineResponse20026EmbeddedIntrusionDetectionReports `json:"intrusion_detection_reports"`
}

// Validate validates this inline response 200 26 embedded
func (m *InlineResponse20026Embedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIntrusionDetectionReports(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20026Embedded) validateIntrusionDetectionReports(formats strfmt.Registry) error {
	if swag.IsZero(m.IntrusionDetectionReports) { // not required
		return nil
	}

	for i := 0; i < len(m.IntrusionDetectionReports); i++ {
		if swag.IsZero(m.IntrusionDetectionReports[i]) { // not required
			continue
		}

		if m.IntrusionDetectionReports[i] != nil {
			if err := m.IntrusionDetectionReports[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("intrusion_detection_reports" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("intrusion_detection_reports" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inline response 200 26 embedded based on the context it is used
func (m *InlineResponse20026Embedded) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIntrusionDetectionReports(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20026Embedded) contextValidateIntrusionDetectionReports(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.IntrusionDetectionReports); i++ {

		if m.IntrusionDetectionReports[i] != nil {
			if err := m.IntrusionDetectionReports[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("intrusion_detection_reports" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("intrusion_detection_reports" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse20026Embedded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse20026Embedded) UnmarshalBinary(b []byte) error {
	var res InlineResponse20026Embedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
